### ISSUE TITLE
Any ideas why I am getting unknown declaration errors?

### ISSUE THREAD

**Issue by Asexual** [Janilabo/ManaPot-Energizer#1]
![image](https://cloud.githubusercontent.com/assets/12243520/21472490/e30f17be-caa2-11e6-99a1-0a053d8797ea.png)

I am simply attempting to compile w/ simba however Tlogs seems to be giving me trouble.

Error: Unknown declaration "DateTimeToStr" at line 53
Compiling failed.

**Comment by Janilabo** [comment]
Which version of Simba are you using?

I have been using Simba 1.2.0 Release Candidate 6: https://github.com/MerlijnWajer/Simba/releases/tag/simba-1.2.0-rc6

**Comment by Janilabo** [comment]
Also, I have myself had some access violation issues with 64-bit compatibility, so I have had to stick with 32-bit version of Simba for now, until I figure out exactly what causes em.

**Comment by Asexual** [comment]
Seems like fixing one error has at least allowed me to compile perhaps including your exact setup would be useful for anyone discovering this in the repository search.

What's your make of this debug?

Error: TMWindow.ReturnData: The parameters passed are wrong; xs,ys -279,-68 width,height 560,314 at line 158
Execution failed.
The following bitmaps were not freed: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]

**Comment by Asexual** [comment]
Strange simba worked on a reinstall of the same version, hell at this point i don't know what fixed the issue but to anyone resolving these above issues just reinstall this exact version and good luck , lol...

http://nala.villavu.com/downloads/master/05a0dc6397ebfbf77d10eae153e58a5050678f87/Simba.i386-win32.exe
